base_lr: 0.1
batch_size: 32
config: ./config/nturgbd-cross-subject/train_spatial.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
freeze_graph_until: 10
ignore_weights: []
log_interval: 100
model: model.dgnn.Model
model_args:
  graph: graph.directed_ntu_rgb_d.Graph
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ./runs/ntu_cs_dgnn_spatial
nesterov: true
num_epoch: 120
num_worker: 48
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 2
start_epoch: 0
step:
- 60
- 90
test_batch_size: 32
test_feeder_args:
  bone_data_path: ./data/ntu/xsub/val_data_bone.npy
  joint_data_path: ./data/ntu/xsub/val_data_joint.npy
  label_path: ./data/ntu/xsub/val_label.pkl
train_feeder_args:
  bone_data_path: ./data/ntu/xsub/train_data_bone.npy
  debug: false
  joint_data_path: ./data/ntu/xsub/train_data_joint.npy
  label_path: ./data/ntu/xsub/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/ntu/xsub/dgnn_spatial
